version: "2"
services:
  microservice:
    build: .
    image: cloud-native-go:1.0.0
    environment:
    - PORT=9090
    ports:
    - "9090:9090"
  nginx:
    image: "nginx:1.15-alpine"
    ports:
    - "8080:80"
    links:
    - microservice